---
- name: Create instances
      os_server:
        cloud: ospcloud
        name: "{{ __openstack_server.name }}"
        state: "{{ __openstack_server.state }}"
        image: "{{ __openstack_server.image }}"
        key_name: "{{ __openstack_server.key_name }}"
        flavor: "{{ __openstack_server.flavor }}"
        security_groups: "{{ __openstack_server.security_group }}"
        nics:
          - net-name: int_network
        meta: "{{ __openstack_server.meta }}"
        userdata: |
          #!/bin/bash 
          curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pub 
          cat /tmp/openstack.pub >> /home/cloud-user/.ssh/authorized_keys
          curl -o /tmp/openstack.pub http://www.opentlc.com/download/ansible_bootcamp/openstack_keys/openstack.pem 
          cat /tmp/openstack.pem >> /home/cloud-user/.ssh/authorized_keys
          curl -o /tmp/internal.repo http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
          cp /tmp/internal.repo /etc/yum.repos.d/internal.repo
      loop: "{{ osp_servers }}"
      loop_control:
        loop_var: __openstack_server

    - name: Add floating IP to instance
      os_floating_ip:
        cloud: ospcloud
        state: present
        reuse: yes
        server: "{{ __openstack_server.name }}"
        network: ext_network
        wait: true
        timeout: 200
      loop: "{{ osp_servers }}"
      loop_control:
        loop_var: __openstack_server
  tags:
    - osp_servers
