---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  template:
    src: repos_template.j2
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

#- name: install base tools and packages
#  yum:
#    name: ['gcc', 'python-pip']
#    state: latest

- name: install base tools and packages
  package:
    name: "{{ __package }}"
    state: present
  loop: 
    - gcc        
    - python-pip
    - httpie
  loop_control:
    loop_var: __package
